---
# tasks file for zabbix_agent
- name: add repo
  yum:
    name: https://repo.zabbix.com/zabbix/3.0/rhel/7/x86_64/zabbix-release-3.0-1.el7.noarch.rpm
    state: present
    
- name: Install zabbix agent 
  yum:
    name: zabbix-agent
    state: present  
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  notify:
    - Start Zabbix and Enable it on the every boot
  
- name: Configurate /etc/zabbix/zabbix_agentd.conf
  copy:
    src: zabbix_agentd.conf
    dest: /etc/zabbix/zabbix_agentd.conf

- name: Insert a rule "INPUT TCP 10050 "in the iptables
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "10050"
    jump: ACCEPT
    action: insert
  notify:
   - save iptables
  

##mysql

- name: Create database user with name 'zabbix' and password "zabbix_pass" with USAGE database privileges
  mysql_user:
    name: zabbix
    password: "{{zabbix_pass}}"
    priv: "*.*:USAGE"
    state: present


- name: Create a directory for .my.cnf in /var/lib/zabbix/
  file:
    path:  /var/lib/zabbix/
    state: directory
    owner: zabbix
    group: zabbix
    mode: '0755'

- name: Template a file to /var/lib/zabbix/.my.cnf   
  template:
    src: my.cnf.j2
    dest: /var/lib/zabbix/.my.cnf
    owner: zabbix
    group: zabbix
    mode: '0644'  
  notify: 
    - Restart Zabbix

##memcached

- name: Install nc 
  yum:
    name: nmap-ncat
    state: present  



- name: Create a directory for /usr/share/zabbix-agent/scripts/
  file:
    path:  /usr/share/zabbix-agent/scripts/
    state: directory


- name: Create a directory for /usr/share/zabbix-agent/
  file:
    path:  /usr/share/zabbix-agent/
    state: directory
    recurse: yes
    owner: zabbix
    group: zabbix
    

- name: memcached.sh  
  copy:
    src: memcached.sh
    dest: /usr/share/zabbix-agent/scripts/memcached.sh
    owner: zabbix
    group: zabbix
    mode: '0751'
  notify: 
    - Restart Zabbix    

- name: memcached.conf  
  copy:
    src: memcached.conf
    dest: /etc/zabbix/zabbix_agentd.d/memcached.conf
    owner: root
    group: root
    mode: '0644'
  notify: 
    - Restart Zabbix   